### ISSUE TITLE
slightly corrupt json + duplicate summary/body

### ISSUE THREAD

**Issue by HolyStephano** [Sweets/tiramisu#10]
I'm using [tiramisu-git](https://aur.archlinux.org/packages/tiramisu-git/) from the AUR and notifications I get seem to have slight issues with the json for some libraries.

[This file](https://f.cloudninja.pw/tiramisu) shows the raw json coming in (using lua to write a small parser) and you can see in the hints, there's a trailing comma which causes some issues, and on apps like spotify, there's a leading AND trailing comma in the hints. I'm able to fix this in a super hacky way in lua 
`notification:gsub("{ ,","{ "):gsub(", }"," }")`
But this is  obviously less than ideal.

On top of this, body and summary seem to be the same value, which can also be seen in that file

**Comment by cglindkamp** [comment]
Maybe this isn't fully fixed. I did not look into the corrupt JSON issue, just the duplicate summary/body.

**Comment by Sweets** [comment]
This needs retesting due to a major rewrite. @cglindkamp do you think you could do some testing?

**Comment by cglindkamp** [comment]
I just did a quick test of the default_output() variant, and the newline is missing after the body line. apart from that, it looks good. Verifying the JSON output should probably done by @HolyStephano

**Comment by Sweets** [comment]
Tested and this appears to be fixed. Reopen if not.
