### ISSUE TITLE
When not using PRINT_JSON and actions is empty, "actions:" and "summary:" are on the same line

### ISSUE THREAD

**Issue by cglindkamp** [Sweets/tiramisu#14]
Current status:
If there is no "action", "summary:" is on the same line as "actions:". If there are multiple actions, the first is on the same line as "actions:", any further ones are on their own line.

This inconvenient to parse, so there always should be a newline after "actions:". The same is true for "hints", but there always seems to be at least one value (urgency). Multiple solutions come to my mind, which I would even implement myself. But I would like your opinion, before I implement something and send a pull request, which isn't going in the right direction.

1. Always add a newline directly after "hints:" and "actions:", the items themselves each are on a new line. (I'm using this variant locally).
2. No newline is between the items, so there are all on the same line as "hints:" and "actions:".
3. As it is now, but a guaranteed newline after an emtpy "hints:" or "actions:" line.

**Comment by Sweets** [comment]
Ideally a user would parse the output based on the label and not the line number associated with specific attributes of a notification, the same way that when doing JSON parsing, a parser would return NULL for an attribute if it does not exist.

I'm not against adding the newlines, I just didn't think that a user would be parsing (or should be for that matter) based on line numbers and not labels. If you feel it necessary though feel free to PR it.

**Comment by cglindkamp** [comment]
I'm parsing based on label, I just assume they start on the beginning of a line like this
```
actions: foo:bar
summary: baz
```

But if actions is empty, it looks like this:
```
actions: summary: baz
```

Here a parser would assume, that I have an action with the key "summary" and the value "baz", an no toplevel summary. 

With always adding a newline after "actions:" and "hints:", both examples look like that:
```
actions:
	foo:bar
summary: baz
```
```
actions:
summary: baz
```

Line numbers wouldn't even work, as there can be an arbitrary number of hints.

**Comment by Sweets** [comment]
I see what you mean now. I wrongly assumed it was based on line number.

Honestly, I really hate the `output` label in `method_handler` to begin with. I'll probably rewrite it sometime soon. In between now and then if you feel like PRing it to fix it you can.
