### ISSUE TITLE
Notifications don't work with Chromium & Firefox

### ISSUE THREAD

**Issue by ahmedkhalf** [Sweets/tiramisu#20]
WM: bspwm, Distro: Manjaro
**How to reproduce:**
1. Kill all browser windows.
2. Start Tiramisu with terminal
3. Open browser
4. Trigger a notification to apear
5. Notification displays using the browser ui and tiramisu doesn't detect it / catch it.
----------------
**Why I think this is a tiramisu bug and not a browser bug:**
When I launch dunst the notifications work just fine and it uses dunst ui instead of firefox ui.

**Comment by Jokler** [comment]
As far as I know `tiramisu` has to advertise that it supports actions for that.

**Comment by Sweets** [comment]
@Jokler From what I've seen, there's no spec for whether a notification daemon does or does not support a specific action. So this wouldn't be true. A notification is what describes actions, not the daemon. The daemon _does_ however have to have an action invoked signal handler, and tiramisu doesn't have a signal tag for ActionInvoked in the introspection XML. This is just speculation at least, I'd need some more testing to be able to say for sure.

**Comment by Jokler** [comment]
That's what I meant then, I don't know the details of how D-Bus works.

(As note on the side, Firefox also uses its own notification code so my guess is that it does the same check as chrome.)

**Comment by The-Compiler** [comment]
FWIW right now, Tiramisu doesn't implement the [GetCapabilities call](https://specifications.freedesktop.org/notification-spec/latest/ar01s09.html) at all, which will likely trip up many other programs as well (might well be the reason it breaks with Firefox?).

But yep, Chromium also [requires](https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/notifications/notification_platform_bridge_linux.cc;l=495-498;drc=1aabf3b424f570b8e0c99d8a5210fbec0955f6bf) both `body` and `actions` (which is a [controversial move](https://bugs.chromium.org/p/chromium/issues/detail?id=676220#c66) on their part...).

**Comment by Sweets** [comment]
Right now I'm looking at rewriting tiramisu from the ground up. There's some things I'm a bit discontent with, but with the rewrite will come GetCapabilities, and hopefully the end of this issue as well.

**Comment by Sweets** [comment]
Finally getting around to this now--I just finished up rewriting most of tiramisu, and hopefully when I push these updates to the GH this will be fixed.

**Comment by ahmedkhalf** [comment]
The latest version works on Firefox, so thanks, also timeout -1 means infinite time right?

**Comment by Sweets** [comment]
> The latest version works on Firefox, so thanks, also timeout -1 means infinite time right?

Excellent, and correct. If possible would you (or @The-Compiler) be able to test for Google Chrome as well?

**Comment by The-Compiler** [comment]
Hm, I've just tried with the latest git master (33137ffb3b62908fb2afbefa9cfee82ea658ea72), and both Firefox and Chromium don't seem to work for me.

Looks like `GetCapabilities` still isn't (properly) implemented?

```con
$ dbus-send --dest=org.freedesktop.Notifications --print-reply /org/freedesktop/Notifications org.freedesktop.Notifications.GetCapabilities
Error org.freedesktop.DBus.Error.UnknownMethod: No such method “GetCapabilities”
```

I'm doing `git clean -dxf && make -j16 && ./tiramisu` so I'm pretty certain I'm in fact running the latest code - what am I missing?

**Comment by oc1024** [comment]
Not tested with Firefox, but 08c5531 still doesn't seem to work with Chromium, and I get the same error message if I run @The-Compiler's command.

**Comment by Sweets** [comment]
GetCapabilities added to Introspection XML. Again, it'll need testing, but now dbus is aware of the ability for tiramisu to respond to GetCapabilities.

**Comment by The-Compiler** [comment]
Seems to work now, thanks! :+1:

Testing with https://www.bennish.net/web-notifications.html and Chromium:

````
Chromium
file:///tmp/.org.chromium.Chromium.la3BLW
0
Notification #2
www.bennish.net

This is the text body of the notification. 
Pretty cool, huh?
#actions
urgency=1,desktop-entry=chromium,image_path=/tmp/.org.chromium.Chromium.iCvIIp,image-path=/tmp/.org.chromium.Chromium.iCvIIp
25000
```

with Firefox:

```
Firefox

0
Notification #2
This is the text body of the notification. 
Pretty cool, huh?
#actions
desktop-entry=Firefox
-1
```

**Comment by oc1024** [comment]
Chromium is also fixed on my end, thanks!
