### ISSUE TITLE
Timestamp?

### ISSUE THREAD

**Issue by Barbarossa93** [Sweets/tiramisu#23]
Hello,

I was thinking what would be nice to include as part of tiramisu's output would be to include a timestamp. It would be useful in providing some sort of history functionality to the notifications (and scripts that employ this would be simplified when the timestamp is already generated instead of having to create it).  In terms of the actual implementation, maybe have tiramisu include a timestamp in seconds since the UNIX epoch? This way, users can extract that information and change it to 12/24 hour or whatever format they desire.

I'm curious to know your thoughts.

**Comment by Sweets** [comment]
I'm not entirely against the idea of a UNIX timestamp, but it doesn't make sense to me to put it in tiramisu.

The idea is that you pipe tiramisu's output into another application, but there's (virtually) no delay between the time that an external application sends a notification to dbus and tiramisu receiving the notification data from dbus.

So to that, I would say that timestamps would be more appropriately implemented into the application the user is piping tiramisu's output into. Especially considering that tiramisu is really just a means of getting data from dbus to the end user (dbus does not provide timestamp data, that's done by end-applications, see: https://developer.gnome.org/notification-spec/)

**Comment by Barbarossa93** [comment]
That's understandable and makes sense. Perhaps I'll file a request over at gnome XD

I'll go ahead and close this, but if you decide that you may want to implement this feature anyway, feel free to re-open
