### ISSUE TITLE
Glib error: in fresh install

### ISSUE THREAD

**Issue by CarlosLoboxyz** [Sweets/tiramisu#26]
![image](https://user-images.githubusercontent.com/86011416/124312672-b456af80-db3d-11eb-966e-dff8c5b35315.png)

**Comment by Sweets** [comment]
This issue tells me next to nothing.

For future reference (to include making bug issues on other github repositories), it's best to include if a bug occurs or doesn't occur when you change some values, use different flags, change the data you're inputting into the given software, etc.

In any case, in my testing I never got this issue, but I'll try to figure out why you did.
