### ISSUE TITLE
Support {image,icon}-data hints

### ISSUE THREAD

**Issue by capezotte** [Sweets/tiramisu#27]
Some applications (like Telegram and Firefox) do not output icon/image paths, but use the {icon,image}-data hints.

Would it be possible to print a representation of that structure? This way, the image could be saved to a temporary file and fed into e.g. xnotify.

**Comment by Sweets** [comment]
There's nothing in the notification spec that explicitly states this, but I _think_ that just by adding `icon-static` to the capabilities, tiramisu should receive images through hints. I added the capability with bf3e2cd, but I'm not entirely certain. Let me know.

https://www.galago-project.org/specs/notification/0.9/x207.html
https://developer.gnome.org/notification-spec/#hints

**Comment by oc1024** [comment]
Just tried new commit, but no dice (at least with Telegram).

**Comment by oc1024** [comment]
I've created a [patched version of tiramisu](https://github.com/oc1024/tiramisu) that prints a base64-encoded representation of the image to stdout. This is good enough for my use and can be decoded relatively easily with the tools I have.

I'm not really experienced with C though, so it might be of questionable quality.

**Comment by Sweets** [comment]
Checked your patch, it’s functional, so I’ll adapt it. Or if anything, you can PR it and I’ll just refactor it.

**Comment by Sweets** [comment]
I've committed changes in regards to base64 encoded images. It does need testing as it's not a one-to-one with the patch you've created. Some refactoring was done, some functionality very slightly changed as well.

**Comment by capezotte** [comment]
Just recompiled from master. This as an output:

    image-data=-1:-1:0:0:0:0:

And these warnings:

    (process:8808): GLib-CRITICAL **: 14:59:54.665: g_variant_get: assertion 'value != NULL' failed
    
    (process:8808): GLib-CRITICAL **: 14:59:54.666: g_variant_get_type: assertion 'value != NULL' failed
    
    (process:8808): GLib-CRITICAL **: 14:59:54.666: g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed
    
    (process:8808): GLib-CRITICAL **: 14:59:54.666: g_variant_get_fixed_array: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_ARRAY)' failed

However, the program doesn't crash, only the image-data output has no actual data.

**Comment by Sweets** [comment]
I did notice a typo and have it fixed with e28b181. I doubt that's going to completely fix the issues given, but worth a shot. I'll have to look more into it once I get off work.

**Comment by capezotte** [comment]
Exact same output and error message.

**Comment by Sweets** [comment]
I didn't figure that it would.

**Comment by Sweets** [comment]
Working on this right now.

**Comment by Sweets** [comment]
Alright, fixed up the base64 not showing up at all. Now base64 encoded data does show up, but on my end Firefox can't disable the image because of errors, presumably because of another porting issue on my behalf.

Still working this.

**Comment by Sweets** [comment]
Taking a closer look at your implementation, even the base64 encoded data it's outputting is incorrect.

The image data it's extrapolating is correct, 160x160 with rowstride of 640, 8 bits per channel and 4 channels, but the actual data that's in memory being encoded is incorrect it seems.

If I had to guess it's from `g_variant_get_fixed_array`, but I can't test anymore tonight to be able to say for sure. I really don't know why this is, honestly. I can tell you that the expected and real lengths are both 102400, and data _is_ being output, so we know that the call to get_fixed_array is at the very least returning the correct data length.

Maybe it's the pixeldata. At this point, I'm just guessing. Like I said though, can't work on this anymore tonight. I'll resume when I can (presumably tomorrow when I get off work).

If you want to toy around with it and output the encoded data to STDOUT, I've pasted the expected base64 encoded data below. You can view the data in the browser by prefixing base64 encoded data with `data:image/jpeg;base64,`, to which you will see a rather lovely image.

```/9j/4AAQSkZJRgABAgAAAQABAAD//gAEKgD/4gIcSUNDX1BST0ZJTEUAAQEAAAIMbGNtcwIQAABtbnRyUkdCIFhZWiAH3AABABkAAwApADlhY3NwQVBQTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLWxjbXMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApkZXNjAAAA/AAAAF5jcHJ0AAABXAAAAAt3dHB0AAABaAAAABRia3B0AAABfAAAABRyWFlaAAABkAAAABRnWFlaAAABpAAAABRiWFlaAAABuAAAABRyVFJDAAABzAAAAEBnVFJDAAABzAAAAEBiVFJDAAABzAAAAEBkZXNjAAAAAAAAAANjMgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0ZXh0AAAAAEZCAABYWVogAAAAAAAA9tYAAQAAAADTLVhZWiAAAAAAAAADFgAAAzMAAAKkWFlaIAAAAAAAAG+iAAA49QAAA5BYWVogAAAAAAAAYpkAALeFAAAY2lhZWiAAAAAAAAAkoAAAD4QAALbPY3VydgAAAAAAAAAaAAAAywHJA2MFkghrC/YQPxVRGzQh8SmQMhg7kkYFUXdd7WtwegWJsZp8rGm/fdPD6TD////bAEMABgQFBgUEBgYFBgcHBggKEAoKCQkKFA4PDBAXFBgYFxQWFhodJR8aGyMcFhYgLCAjJicpKikZHy0wLSgwJSgpKP/bAEMBBwcHCggKEwoKEygaFhooKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKP/CABEIAKAAoAMAIgABEQECEQH/xAAbAAABBQEBAAAAAAAAAAAAAAAFAQIDBAYAB//EABoBAAMBAQEBAAAAAAAAAAAAAAECAwAEBQb/xAAaAQADAQEBAQAAAAAAAAAAAAABAgMABAUG/9oADAMAAAERAhEAAAHD8q8nqrFNFtX7lZWcRNogjXChCR1k2IssmuZVtzzeVDuR3Yo7uwwyo+nooybiKGztm+bnZFbi5kCCtaNqM7aKiqreHCkqmps5XVA9y8Dyo7bCO5x9R5sNZEtRwB0OM3OBjBJ6SoTRw4w/Ed50J9K8/wC7nh2eE1LppeVeejXcu2Hcrh7KzxSblrSDL1/O0enWhxdB4GFE1Tc2AEaOQz7pqpjS0U95azndAtcq7Yt3Pn73U7mhfjzPpGX2cuWQWV6exlfXibaUXucnlwlkkzpmGuojJsuk6Bjc/hsWrll9Amqy8Jh6vX8z2w8y9VswzcQlqahyEs4npU4tOwooTTaLSVZOVY1cuGJVV5/okd3ACdMHKdPh6CCtDClgebDUI8MWd1B1yCyimLz3TjGkqDR9JxGG5e5vo+53A0NAJOW82elcpDkKPzMVAWHx9UTFg14DVLXtIjUf2zEe3DCuNaKXt4fR7SSvCMrlhs+XPZ/QBM9RHvuKr5ZNoQxltVmJ1m1iXv5u1JjmI0ld4ehsimlV/J20QstSGygs9QWoltqszJH1h1jtI6skVX7LbZaGlmjkXf/EACgQAAICAgEEAQMFAQAAAAAAAAECAAMEERIFEBMhICIwMRQkMjRBM//aAAgBAAABBQLu/c/mdP8A7BdVnkQ9j9t+wlGJbewwVRQmlcNN6NVtiNVcH+28H5wumDQGhaqqhQtLKyqNVoqFIdayrWPVKbQ4+xwLTp+CtELgzkERVDNaAs4eRrauK2ELHv8AaW7mPdxsHzA3MLip8vKB9Tzc7Df4663a5qq+CWDZajkMvHNbA6JadPsNlHxHbkRXS+o1kxm4i0m1sLGFcsdZ60EmVR5EyKijTo7fIdrF2C+mTcXGLJg4VWKr206tNRasAg+lueZNYsmRT426R/2+IgEyLOCM/wBPTudmRWbocjxi/J8hss3bjZSy3MWw/quD2XhlzXBTpS/uPkBH1yTFDTpNaU4z18o+KA11V8TAew9LwjXZ19NWJznNhMnQs6Uf3Xz6Lhpqyt7ckKKlVtDySxwYTyuQ8R1P6iKuUakiZoHj6T/a+fR7lhqTix32cmXW6GPjMVre+i2y+wtSQ6n85gBr6TV9E18rQd2ZuQ9fT7PJg9gqlrM+iiZWZj3kMJX2CeWyutax8/8AbV2ej2kYZs9B5xNxbpygviMoIZGp3x/zGqCr9mz0OkjnT/iDkdcFyWYzmYF9ge00X+WvhkfjoS6ocfUG4P5lnOhhbXWTrUEwqW5/aupsevpFT149vot7jzc5TcWN1ZakxrBfT8D6HZEZzjdKd4cetRcJemxZ6O+xgWWfws9rQhpxhlWpEzYt1bS2xa0ycl72o6bkWyjpVSStErEMu9S55Z7mpqa9y7+NFHs+zAIonEEWYVVkY6i92mRordWUjzU12LaiJ7g7ARRBBGO2Hcy5OSsxSPTuMuoTDsyqvjD+T+ANKBAsUQQT/8QAIxEAAgIBBAICAwAAAAAAAAAAABEBAhAEEiAhA0ExUSIyQv/aAAgBAhEBPwFE4mUeSz5ImOibfWE8PgjzfjUZHYli9UVyjV9VK9yho3k2g3RJHzlGro0bIrhMtD6NiP6zBqeqMiXwmS33wvXdVEVmllOOvZMR6JJl8dRWu+ZwxkyuF9X46ezy6+1v06KWfzhYkYzzUteOstEXeJshvh//xAAiEQACAgIDAQACAwAAAAAAAAAAAQIRAyEQEjEgEyIjQWH/2gAIAQERAT8B5lkUS+zOvzZZlzXqIvSM6FKxQY1Xw9ocDpsf+EWYZ9lTMi1zZH0cdWbZHF/Z+OTZ0cS7hvmyMqVsy5HIQpuiD/ZSY8iZdw5sjvRkxddiNvSIq1tFF6r4TMjuB1oxylehSa9H9N/xkRY+Kb8POVibI4kjNGnZBc40Sin6PEjD1xvfPumdOpQo2JV8f//EAC4QAAEDAQcCBQMFAAAAAAAAAAEAAhEhAxASMDFBUSJxEyAyYZEEQoEjQFJiof/aAAgBAAAGPwLIaquCo4fsOhtOVWvdEjiirdy1RNc0Ptqn+KwsEBdaOzUdpN1BdrLV75MNElC0teq144UN/JuLnVKEqfhV2RugquTi1RrqoVPS1SVidupKKi8KuoyKKuqPK/1Bg/KDn/CouTcZob3jIC6dlBOuqAbodFifV/KgqWOnzHtkAbm4YLNzwNcIUtbYtYOdUTb9T5gNCjw8KmTRS+T2XSY7qID16YTUe2QZ6uAuvXhYbMKU50GT9w2WmJTaQ0I2jtPtVm5vZGolQ5GRIUf1yH/UvElphoTAN3VWFul/pCawanZVdW7abm0rkusC7C49TVUDupuovdPtDIcRROa57iPdBdWt0nZeJ75AcKELD4lVYk64YvxOWF1TwF6HMPIWt7WRQ6qGCBkQqbItOzrjJUAw1E+NPcITZzG4NwuDvuOVKt+4UKFS71KTc0HfMt+93tdJUtAvL3Cm2XLLNx9wFaY2kSaT55OiMWLp2rRNeIqPLJ0vhoJ7LFbHAON1ZgDpbplMadVz3XUz4VHLE80UuMM2C9OAcuX6pLyos2ho9ssPf+B5arSO3mwupwVXQ7+bFafGb0/CjVvBWKyqONxfRS6rsn//xAAlEAADAAICAgEFAQEBAAAAAAAAAREhMUFREGFxIIGRobHhwdH/2gAIAQAAAT8hhPGnlMiDNdNhpp8sW4/uLKq8GMnjBPCwIWhMeEMxXzbCQ0Sn70JY1kSlGnWwuSlcr0WFdBwtHj6OCeUvCNBLEyK2mBMGsmtm7KUzT4ELSaSWzTdQXHCONCa8J9rAw+NnaILE/TwJTxMl6eZqCaTYuHsZCf8AUkNL4R69z0LEZK8D0dSwgrQy2WqTX8Y5RnKK2ClLEySnnjwsIRQuBBivoHLKvbEnCTUvfAnB4HbJohE7PBl62YihlxgaefsLF3GT6IJkSFwzgw6vQu1XDLLDvbM72rH8ELLsx0J42tIc4Om2PVYhJegc01lH/Ci9Kf0pZyIL5GQamSr0fsTscqeinChHLEx99sNUY7GFGPZeUZIzkfrdyL8rIxa4ejTWBPMEjDJZiVmUfg0Vi5H3D60aHFrMkzf+ReTMOJTlGZ8QlVRLEbEqi8JIbh3tMomr+iS95TMx0J5hFCYELehqFp4WxhX9RHJK1vtmoeWdZSRX/gqeHRodEoeiyjmJ6H6llhGbfccCmRUUFZKKwj7oIQhCZJnw9UJxdbECtbHWRWNgm6dqXa32xKWrYCMMx8pCUTaXssDPVXyVDitiW/TRCEyQk14SJKz+Q557a4MRHaOvxjnJZ6DqW5N0MlDtRKYaW2zBGDMYTqPlNLInJnhCEJkg83bO0PqPgWdob5WB4RVRh1rSHFGvfAfF8dR55+4w52XBVq/UGhCliIQhBETJgWKZpkNv0NlLp9zdF5cBnkjkaReaRoRSbbRhKce0xsha8MoYfgg0QhPCEsGoZ0Iw/ScvwJu22h/WKUlH1saL8xL2PkkUZETCWFNEIQhBhoQtDxU9M3a1f4SZodlCQ8tQWDGMyD4HTY0VMWTopeJ4hPoWhaQfYMf3uEpbOhks5EaW20JlyxRyzuj7FktB7kDTtpzxCEGTmpJts5JjBet6Si5ZdxyMfdaRvvkxFARkq2NJ0RdFjAzGWj4ml3HokKpUuIt717Y1on08DfIv7GGJfpJjdvo/Q2vStI9LsSDI5MeReV4obIRhoIZUJ28z0DZOENV+RUpKumJtn3WIDJeGZpjZAwOr6iZTErGcDjIlP4PcXx/7Nm+dIRQlBRTEGoxmlRT276FLBm9TF21nHJqeCiZXgr/yCOVZSyGo9+PV4Uhsf//aAAwDAAABEQIRAAAQ/D+28y2HYlYltMs3BZQJkcSgjzikaodWJF/GkKfjK6n1U0HP0nsMxo0crXuNAWT3m49x2xGlmfYOqEIdsURb5zwh46xJjvVHaOkO/8QAHxEBAQEBAAICAwEAAAAAAAAAAQARIRAxQVEgYXHB/9oACAECEQE/EH7Q5yHfUXtaBLsjdvU/q6sJlyPeF80mep+MI9tufNkuhsZa4n0Eh6y36TVzxyDYAfuWMRwXDhCNWS6eoBkvV/IiFfEf2Mj8Rt0sH0vqsTBb4EdYewbey85duEMfDsEDP5kNF1B9T4aO+Q7ZyzF7LnTx1ZrmzKBct0/rsFg/1Lo9vGLMmB2ENv5ss8IthLSydnfdg7KW/h//xAAeEQEBAQEAAgMBAQAAAAAAAAABABEhMVEQQWFxgf/aAAgBAREBPxAj4Wxe2NtyfVlRy0bPu/kYY9ryKWamV4JYvjeTluFvuPCXcJLj6sbGz1e0Iu7LNmacFk/S+tf8Lc1xjAyEjKRg5bMJoIDZOwcEux2BkdLT6lfhl7fMgHYtDPs2mTcLlznDPuXkg6XX/kDqFng+CLutvq7bP5a3izExiTzAZmxyx3hhg9XSukygPE6wBfkjwuCNvqy2HWSyQEbWni6s0A5LLJt//8QAJhABAAICAgIBBAMBAQAAAAAAAQARITFBUWFxgZGhsdEQwfDh8f/aAAgBAAABPxBsY3LAERrB/wAgxe5VzdUpwyqzuW6jNuxPVjCx4HCSuyGCrSuwNXcGS9QZrvjUHYE9pjjJcr7tT4SvUWzdTRDvMFYYiZYemOcktvPxDwQyul5WAmL3iLyniB47ALivHmKSWUrlgERXkVXEonCHPEpCSz2O4/4iGKvdtyqlAHiN7qV78yv/AGZG9wDJV0buBovX5m/z94pBKaA5hOgCVwDnK8wWxqoNwCq2GZXg9wF84Dr/AKxJFDZtmbldAjr3LtXAsXzfcoFQ2WHhuCAV9FX7I/4CwcPklbwepVtNEPeuZWfXmWHyiC8/WBd/eIaaxc0W0DdwxaP5e7hDUb5FyEoo63f5igoWC7O1eYgSzRg/xFe/2x5lxqLGmSE8oKPyHmLE6C9eSbbiVfZASENX2RjshLIcX69xJV/5coAhaHMx7tlU+TEjpGSyLYAWU2+PUyiSeglZrYTn/FyxipdOLYMynRf2Jlj5l2ymYBkMlSwRWr3KZV7p7lEN3iXsrQ3ywUumbycX5j2lVv4gN/uBbiGSN9EFRteZZgx6joeVW1Fsytm1f7MRryUccEShIKHLqortrTF08fRCJwBTAggRRS4z34JcVpuvb+uIMNdw5KZv3GFHJWHzFsy5UyDwP7mzNMJXCfMz+pQHTxA2X+pTARgEAGGLczCWKhC79oDSymYdHmBiUDK8r0EOHkLunxGgzhYlshZNr9QtQYsI+1FiorcY+EKJnNOSUsvMuyClqLa7zHLW4nEpW7nhAFrMToH2YlA47WXYDKHDi4plBWO4I6OMPfEpQHh35ChXxHjWWzYA2DoztiNd2LE/qDkRZHIfn5hMvOzQ9EAUii1fd5IHmjaQfuHmH2jUqV0MkutOeg5GK1Kzm/pKcTa2pgDiVz45jN3V1xF2q6AvbL6xFCUL0+Imx0Zlt2/iClRsrmEsis3Eqk9LuAKk4WU/HEAM1thWOLZMOTumCmWxDI4T8SxKiiyexUdvZy1/c3hlcDTmyJSpuXxFQ96mbU0icjNaZRd80y3Jq9O4pBwAbZX85hJoAygOV/FwU0DR58ygwG1jSlT5iCd5DMbXBQqNZz4i8NGU4jLBakrdXzMOAil32al4TdxFEeNTxK9iCJ81Z+I74mtbnVqY8TPVK7gZzj4g4M33wQpqxFOFJ9tdQTSXvN+4JCAsTmIMuCeSeJbjTQIWNhNJqJRJwtHwvEDXIO/gJWQEF8+JdKDGWnCQAd2U9GSY58zScMTWUw4XmZbHqGjdtywbQakTJk1BmvDlPHncsEbS+x+JVacS65mD8KV3MoESkY9nuMKNKMv7MYjcwcIqBqmX3Ras1m8x0BnrTcdosBgZaVrmes84Aqs8Q4B7uUtWu4RAAaR+0SiS4sPoqNth14o/m5Tmwyu9VqJWjTIafjzHFWUwr5Rg3MU+umFGZ6/ISVKpwTqAUSqvmMG2Tegwf8D9f84mLgHznEuVlQbW7uUoS228V19ogK0iOrV/iM3iiXqbiHt5jhK8cyqlxDeIHT0Zh0Vd6Si47AgDARYIAoFB1CfWYXMn+KCZvw8zycQI/EC2z5IAFobOoKknLvymng4SZmbPWoY9RY4lAn4sq46QdYSyKY0magOjw+5iDXLLvNn0iaYEe0rr+HhDHNBEuqMR+hGFuNal8TpZFlQBNKMqDeH4itL5EXUDtMM4DMwoJ7mde6VDJaYjpPEjmHXEhPklsc0QF2DySqxH5R8JpDgpaKCBalXBzAC+0JX2jsNbIH4JlgpRBVq7Wty2gYCiGxAqYmVfTH+T4YkqsmSHC4tbKOLahGLxXUKBcKDm4B0lwMm6+LlBnhVj9dxOu7sn0ZUYB2oW0d2ZV0HLFBoIYBeL7ajA2QNh+UOFuU/15YA6CcZCQ6a6Y7LcXfZMQ4YxWAcQCvZjUd/PEDYAlFNeZblNYgL1Zcq3C+Ygr9ksFNynLMhrMpH6iwmcXOiPpqZXmJVdrOSZQYHzLR2rEsO78ShV/wBUT/U0mtwdV6SXw4Y0K1GnEqQvVDL6h4FmXzXT+kp8b7gFP/TBbdxgY8E4Ql25gxFIaGGhFqKGqF1x3DWK8m/SLtbUSx8nD5gCDy7eFOTyRxlT7TYrUVcXoC36QbI4OQ+PPmLI2OLgVyeLgBnm4ltYlX3TwUkre4rpP//Z```
