### ISSUE TITLE
[QUESTION] How to output in JSON

### ISSUE THREAD

**Issue by NumenHackerCracker** [Sweets/tiramisu#31]
I'm sorry if this is a stupid question, but I really have no idea how I can tell tiramisu to format its output in JSON. I've looked everywhere, no man page, nothing on the wiki page, all I could find is some function in `output.c` for formatting as JSON called if a variable `print_json` is non-zero. How do I set this variable? Some argument when running tiramisu? Compile time option?

**Comment by vredesbyyrd** [comment]
Trying to figure out the same thing. I have looked through the source with no luck. It appears `config.h` was replaced with command line flags so it should be a set at runtime. Its not an env variable, eg `PRINT_JSON=1`.  

@Sweets How is outputting json set? Thanks for your time!

**Comment by Sweets** [comment]
Outputting JSON was removed during the large rewrite I did a bit ago. It wasn't meant to be a permanent removal though, so I'll add in a flag to bring JSON output back, likely `-j`.

For the time being though, you can use the `-o` flag. Expand as necessary.

```
tiramisu -s -o '{"summary": "#summary", "body": "#body"}'
```

**Comment by vredesbyyrd** [comment]
Thanks for the heads up, and who knows why I did not just think of using the `-o` flag, uhg. That will work fine.

**Comment by vredesbyyrd** [comment]
I did some light testing and so far `-j` is working all good on linux. Ill report back if I run into any issues.

**Comment by Sweets** [comment]
Sounds good. For the time being I'll close this, but feel free to reopen, comment, or make a new issue if you run into anything.

**Comment by OliverLew** [comment]
@Sweets reporting two issues here:

- A tiny issue in the help message itself: there is no new line at the end of `-j`.
- Use `-j` option *randomly* crash with "Segmentation fault". I couldn't find any pattern when it crashes.

Note that the crash seems random to me. I am not sure if I am debugging it right (I am not familiar with it), but I tried to catch it once in `gdb` and the result is as follows. The notification is sent by `notify-send test`. The last `print output` is suspicious to me, is there something wrong with that?
```
$ gdb --args ./tiramisu -j
GNU gdb (GDB) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./tiramisu...
@(gdb) r
Starting program: /home/oliver/.cache/paru/clone/tiramisu-git/src/tiramisu/tiramisu -j
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff78d1640 (LWP 2156283)]
[New Thread 0x7ffff70d0640 (LWP 2156284)]
[New Thread 0x7ffff68cf640 (LWP 2156285)]
[New Thread 0x7ffff60ce640 (LWP 2156286)]
[Thread 0x7ffff70d0640 (LWP 2156284) exited]
[New Thread 0x7ffff70d0640 (LWP 2156503)]

Thread 1 "tiramisu" received signal SIGSEGV, Segmentation fault.
strsanitize (_string=0x7fffffffc850) at src/notification.c:309
309             output[output_index++] = string[index++];
@(gdb) print output_index
$1 = 1
@(gdb)
$2 = 1
@(gdb) print index
$3 = 1
@(gdb) print string
$4 = 0x55555557aec0 "notify-send"
@(gdb) print output
$5 = 0x0
@(gdb)
```

**Comment by Sweets** [comment]
Yes, output is supposed to be a string, but it's 0 in the debugger. It's kind of interesting that it does this seemingly randomly. I can see _why_ it segfaulted, sort of. It seems to me that the length of `string` is probably 0.

I think I may have some inclination as to why -- I'll need testing on your part with the most recent change that is about to be commited. @OliverLew

**Comment by OliverLew** [comment]
@Sweets It should be the `quotes` variable not initialized. Clang compiler gives the warning. And `gdb` shows it's -14320 when crashed.

**Comment by Sweets** [comment]
Just pushed update that initializes both

**Comment by OliverLew** [comment]
Tested a dozen times, it's not happening again. I think that was the issue.

**Comment by Sweets** [comment]
I refuse to close this issue given that I've reopened it like three times and things keep popping up from my lack of brain cells lol.

I'll keep this open for a few days -- again, if something happens let me know. Thanks for your help so far.
