### ISSUE TITLE
JSON mode doesn't output valid json

### ISSUE THREAD

**Issue by Terramorpha** [Sweets/tiramisu#41]
The json output uses the `'` character as a string delimiter, which isn't part of the [JSON standard](https://www.json.org/json-en.html)
It would be nice if you could pipe the output to `jq`, for instance

**Comment by Terramorpha** [comment]
also, hexadecimal numbers don't exist in JSON, the `urgency` field is outputted in hexadecimal form.

**Comment by Sweets** [comment]
Pulled #42
