### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by MostHated** [Sweets/tiramisu#45]
I apologize if this is a silly question, but is this usable along-side a systems notification system (send-notify on Pop_OS), or strictly in place of? 

Thanks,
-MH

**Comment by Sweets** [comment]
Depends, some notification programs by independent OS's make their own notification bus for varying reasons. If that system-wide notification system uses the regular notification bus specified by notification spec though (org.freedesktop.Notifications), then it will be strictly in place of.

An example of where it would be used along-side is if you had a system with say herbe + tiramisu, I've heard that's a common use-case among people, but I've never used it myself.
