### ISSUE TITLE
[QUESTION] tiramisu + herbe

### ISSUE THREAD

**Issue by R41LGUNN3R** [Sweets/tiramisu#48]
Hey! Sorry for noob question, im just starting my linux way :). I'm on void linux.
How can I setup tiramisu + herbe? I don't know how to call herbe properly. I've tried `tiramisu -o "#body" | herbe`, no results :(. And I guess, I have to enable that daemon on startup, how to do that?
Thanks in advance!

PS: I don't want to use dunst. :)

**Comment by Sweets** [comment]
Sorry to say, but using tiramisu with herbe is not something I'm actually privy to.

That being said though, from this [gif](https://preview.redd.it/44cul0vkewm51.gif?format=mp4&s=7929418abe15b78194ce17b70538d13436a93513), it would seem that some processing needs to be done in the transitory.

So it'd likely be something along the lines of piping the output of tiramisu into a script that itself calls herbe. Say `tiramisu -o "#body" | myscript.sh`, and in myscript.sh it calls `herbe "(summary)" "(body)"`

That's my best guess though. I've not actually used herbe.

**Comment by unrealapex** [comment]
Here is a snippet of how this can be done for anyone interested:
```bash
tiramisu -o "#summary;#body" | 
  while read -r line; do
    summary=$(cut -d ';' -f 1 <<< "$line")
    body=$(cut -d ';' -f 2 <<< "$line")
    herbe "$summary" "$body"
done
```
