### ISSUE TITLE
tiramisu.vala:46: Unable to acquired DBus name

### ISSUE THREAD

**Issue by mioxoim** [Sweets/tiramisu#52]
I have not clue why it says that spend sometime trying to figure this out on the internet
My polytiramisu outputs either 'Terminated' or 'Trace/breakpoint trap (core dumped)`
`$ tiramisu -s

** (tiramisu:208089): ERROR **: 22:18:18.439: tiramisu.vala:46: Unable to acquired DBus name.
Trace/breakpoint trap (core dumped)`

**Comment by DennisFeldbusch** [comment]
Same for me

**Comment by Sweets** [comment]
Being unable to acquire the dbus name means that there's already a process that has the session name (org.freedesktop.Notifications). Is there a daemon that's already running?

**Comment by xuoe** [comment]
@Sweets: yep, that was it. Had to kill `notify-osd` after uninstalling it. BTW, cool little tool, thanks.
