### ISSUE TITLE
how to decode `image-data`

### ISSUE THREAD

**Issue by wael444** [Sweets/tiramisu#53]
https://0x0.st/of6F.json
this is the json from `tiramisu -j` from https://www.bennish.net/web-notifications.html, how do i convert this to a PNG in use for a notification daemon?

**Comment by Sweets** [comment]
Apologies for the late reply.

The image data output by tiramisu is raw pixel data. So you'll first decode the base64 to a .raw file. The .raw file will need to be converted, which can be done with ImageMagick.

The appropriate information prefixes the base64 of the image. In order it's width, height, row stride, if an alpha channel is used (transparency), the bit depth, and channels. Here's an example with ImageMagick, assuming the base64 as already been extrapolated from the string output.

**Comment by wael444** [comment]
how am i even supposed to parse with `jq`? simply giving jq the output gives `parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 2, column 18`, with `.hints.image-data` it says `jq: error: data/0 is not defined at <top-level>, line 1:`.

**Comment by wael444** [comment]
> The appropriate information prefixes the base64 of the image. In order it's width, height, row stride, if an alpha channel is used (transparency), the bit depth, and channels.

I can see to decode into raw is `jq -r '.hints."image-data"' | base64 -d > image.raw` but since that contains the image information up until the last :, which contains the width and height, im not sure what options to pass to ImageMagick for the rest.

**Comment by Sweets** [comment]
You may not necessarily need all of the information provided. Depends on your application, but a simple image conversion should be something along the lines of `magick -size WxH -depth D rgb:image.raw output.png`, where W, H, and D are your width, height, and depth respectively.

Also, don't pass all of the image-data into a base64 decode. The only thing that should be passed for decoding is the actual base64 data, which is everything after the last separator (`:`). Some string splicing will need to be done.

**Comment by Sweets** [comment]
This all help point you in the right direction?
