### ISSUE TITLE
No way to get hints or actions

### ISSUE THREAD

**Issue by phenax** [Sweets/tiramisu#8]
There doesn't seem to be any way to access `hints` or `actions`

**Comment by Sweets** [comment]
There's not any way to currently. The program does fetch both actions and hints but it does not format and output them. I was thinking of just removing them, mostly because I don't know of any particular reason why someone would use them. In the case of notifications marked as urgent or critical, almost everything just disregards and ignores them.

I'm not against adding them in, and probably will soon then since someone actually seems to need them. Out of curiosity, what hint or action are you specifically looking at that you need?

**Comment by phenax** [comment]
I need it for the web push notifications I get from the browser and also a few of my scripts. Usually involves some url.
Trying to replace dunst with a more modular setup.

**Comment by phenax** [comment]
I can give this a try, if thats okay with you

**Comment by Sweets** [comment]
I mean yeah sure go for it. I'm going to implement it anyways, and it'll probably be today, but if you want to give it a shot you can.

**Comment by phenax** [comment]
Oh thats even better!

**Comment by Sweets** [comment]
Working on this now.

**Comment by Sweets** [comment]
Just on update so you don't think I forgot about this issue, I've got hints being outputted right now. Working on a way to nicely format them into both JSON and non-JSON formats. Going to start on actions soon.

**Comment by Sweets** [comment]
I've pushed the actions and hints now. They're not pretty-printed, but I need some testing before I can fully say they're done (and refactor them and have them print nicely).

That being said, can you build with the latest commit and let me know? (also if you could, screenshot the output with both actions and hints so I can see the output)

I'll start working on the refactoring now under the assumption that it works, but I don't want to fully commit to doing so until I know that it works.

**Comment by phenax** [comment]
I'm getting a leading comma in hints json

![part-2020_07_05_05_28_27](https://user-images.githubusercontent.com/11407672/86522762-75d1da80-be80-11ea-8636-6dab0764874e.jpg)

**Comment by phenax** [comment]
I can't find actions in the output.

![part-2020_07_05_05_40_41](https://user-images.githubusercontent.com/11407672/86522887-32786b80-be82-11ea-934b-739345d2789b.jpg)

with this command
```
gdbus call --session --dest org.freedesktop.Notifications --object-path
/org/freedesktop/Notifications --method org.freedesktop.Notifications.Notify \
  "Hello" "0" "~" "Nice tits bro" "Whoa foobaaaaar" \
  '["21", "world", "nice", "fff"]' '{}' "int32 -1"
```

**Comment by Sweets** [comment]
Just realized that I forgot to `push`. How about now? Also, what are the actions in that `gdbus` command? Or rather how are they specified?

And yes, I know of the leading comma in the hints, that's part of refactoring later.

**Comment by phenax** [comment]
Im getting a `segmentation fault` error.

Actions are a list of even number of strings. Immediete even odd being a pair. [Ref: https://specifications.freedesktop.org/notification-spec/latest/ar01s09.html]

You can use [this script](https://github.com/vlevit/notify-send.sh/blob/master/notify-send.sh) to send notifications with actions.

**Comment by Sweets** [comment]
I didn't need a reference for the dbus protocol, I was asking what arguments in the command you pasted in your prior comment were for actions (I've figured it out though).

I've got the identifier for actions, and the flavor text for them as well. I'll need to add a handler for actions in, but for now it's good to consider it done. I've not made it pretty or anything, working on that refactor now.

**Comment by phenax** [comment]
I pulled from upstream today and json stopped working. Is this intentional?
Also, the key value seperator is `=` for actions but `:` for hints. I think `:` will be more consistent for both.

Other than that actions and hints are working pretty well!

**Comment by Sweets** [comment]
Yes this is intentional. It was part of the partial rewrite. It'll be added back soon.

**Comment by Sweets** [comment]
Not currently home, but I just need one final test before I can close this. If you want to pull and test for me you can.

**Comment by phenax** [comment]
Opening brace for json is missing

![part-2020_07_08_11_45_19](https://user-images.githubusercontent.com/11407672/86884174-d24b2900-c110-11ea-9f26-0da970e3b66f.jpg)
